# Generated by Django 5.2.1 on 2025-06-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annivory_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='media',
            name='post',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
